# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ship.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ship.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nship.proto\x12\tspaceship\">\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"\xca\x01\n\x0cShipResponse\x12\'\n\talignment\x18\x01 \x01(\x0e\x32\x14.spaceship.Alignment\x12(\n\nship_class\x18\x02 \x01(\x0e\x32\x14.spaceship.ShipClass\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\x11\n\tcrew_size\x18\x05 \x01(\x05\x12\x10\n\x08is_armed\x18\x06 \x01(\x08\x12$\n\x08officers\x18\x07 \x03(\x0b\x32\x12.spaceship.Officer\"A\n\x0eRigthAscention\x12\r\n\x05hours\x18\x01 \x01(\x02\x12\x0f\n\x07minutes\x18\x02 \x01(\x02\x12\x0f\n\x07seconds\x18\x03 \x01(\x02\"@\n\x0b\x44\x65\x63lination\x12\x0f\n\x07\x64\x65grees\x18\x01 \x01(\x02\x12\x0f\n\x07minutes\x18\x02 \x01(\x02\x12\x0f\n\x07seconds\x18\x03 \x01(\x02\"n\n\x0b\x43oordinates\x12\x32\n\x0fright_ascention\x18\x01 \x01(\x0b\x32\x19.spaceship.RigthAscention\x12+\n\x0b\x64\x65\x63lination\x18\x02 \x01(\x0b\x32\x16.spaceship.Declination\">\n\x10ShipResponseList\x12*\n\tresponses\x18\x01 \x03(\x0b\x32\x17.spaceship.ShipResponse*`\n\tShipClass\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05* \n\tAlignment\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\x32Q\n\x0bShipService\x12\x42\n\tget_ships\x12\x16.spaceship.Coordinates\x1a\x1b.spaceship.ShipResponseList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ship_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHIPCLASS']._serialized_start=603
  _globals['_SHIPCLASS']._serialized_end=699
  _globals['_ALIGNMENT']._serialized_start=701
  _globals['_ALIGNMENT']._serialized_end=733
  _globals['_OFFICER']._serialized_start=25
  _globals['_OFFICER']._serialized_end=87
  _globals['_SHIPRESPONSE']._serialized_start=90
  _globals['_SHIPRESPONSE']._serialized_end=292
  _globals['_RIGTHASCENTION']._serialized_start=294
  _globals['_RIGTHASCENTION']._serialized_end=359
  _globals['_DECLINATION']._serialized_start=361
  _globals['_DECLINATION']._serialized_end=425
  _globals['_COORDINATES']._serialized_start=427
  _globals['_COORDINATES']._serialized_end=537
  _globals['_SHIPRESPONSELIST']._serialized_start=539
  _globals['_SHIPRESPONSELIST']._serialized_end=601
  _globals['_SHIPSERVICE']._serialized_start=735
  _globals['_SHIPSERVICE']._serialized_end=816
# @@protoc_insertion_point(module_scope)
